@authToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjVhNzNmMmJlLTM4NGQtNDVhOS04ZjUwLTYyZTU2NTcyYzhlMSIsIlVzZXJOYW1lIjoic2FtcGxlIiwibmJmIjoxNjk3NDczMTQyLCJleHAiOjE2OTc0OTQ3NDIsImlhdCI6MTY5NzQ3MzE0MiwiaXNzIjoiVGFza01hbmFnZXIiLCJhdWQiOiJUYXNrTWFuYWdlciJ9.ZfbDXA90DTs_cr5E0FtiBGVgW-gxw7IRs0SdBLnnK2tedhsJ4W6FQ0gurKDEiM1KjsJiIrMz1dhlTLNp4WBc8w

@url = https://taskmanager-todo.azurewebsites.net
@localUrl = http://localhost:5218/



###
POST http://localhost:5218/auth/getToken HTTP/1.1
content-type: application/json

{
    "name": "sample2",
    "password": "123"
}

###
POST http://localhost:5218/auth/register HTTP/1.1
content-type: application/json

{
    "name": "sample2",
    "password": "123"
}


###
GET https://taskmanager-todo.azurewebsites.net/task/empty_dishwasher2 HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET http://localhost:5218/tasks HTTP/1.1
Authorization:Bearer {{authToken}}


###
POST http://localhost:5218/task HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "name": "sdf",
    "description": "afesw",
    "deadline": "10/16/2023 05:16 PM",
    "priority": "low"
}

###
PUT http://localhost:5218/task/empty_dishwasher2 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "name": "empty_dishwasher2",
    "description": "Empty the dishwasher and put everything away.",
    "priority": "low"
}