@authToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIlVzZXJOYW1lIjoic2FtcGxlMiIsIm5iZiI6MTY5NzgwNDQzMiwiZXhwIjoxNjk3ODI2MDMyLCJpYXQiOjE2OTc4MDQ0MzIsImlzcyI6IlRhc2tNYW5hZ2VyIiwiYXVkIjoiVGFza01hbmFnZXIifQ.vOoD8DmTssjKzEY0FU4bJGVBzix4NrZ_PE4vIw3DU1QXOzEePd3YpgPq2TOPYmfuV8c_2GRGTALv0XbZJnBhNg

@url = https://taskmanager-todo.azurewebsites.net
@localUrl = http://localhost:5218/



###
POST http://localhost:5218/auth/getToken HTTP/1.1
content-type: application/json

{
    "name": "sample2",
    "password": "123"
}

###
POST http://localhost:5218/auth/register HTTP/1.1
content-type: application/json

{
    "name": "sample2",
    "password": "123"
}


###
GET https://taskmanager-todo.azurewebsites.net/task/empty_dishwasher2 HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET http://localhost:5218/tasks?isComplete=false&priorities=High%2CMedium%2CLow HTTP/1.1
Authorization:Bearer {{authToken}}


###
POST http://localhost:5218/task HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "name": "task3",
    "description": "wraqg",
    "deadline": "2009-05-05T04:55:00.000Z",
    "priority": "low"
}

###
PUT http://localhost:5218/task/empty_dishwasher2 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "name": "empty_dishwasher2",
    "description": "Empty the dishwasher and put everything away.",
    "priority": "low"
}

###
DELETE http://localhost:5218/task/task3 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json


###
POST http://localhost:5218/task/complete/task3 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json
